pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_13_x:
      node_version: 13.x

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)
- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
